import 'package:flutter/foundation.dart';
import 'package:rentease/models/chat_room_model.dart';
import 'package:rentease/models/message_model.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class ChatService {
  final SupabaseClient _client;
  ChatService(this._client);

  // 1. Get or Create a Chat Room
  // This is for a tenant starting a chat with their landlord
  Future<ChatRoomModel> getOrCreateChatRoom(String tenantId, String landlordId) async {
    try {
      // Check if a room already exists
      final data = await _client
          .from('chat_rooms')
          .select()
          .eq('tenant_id', tenantId)
          .eq('landlord_id', landlordId)
          .maybeSingle(); // Returns null if no room is found

      if (data != null) {
        // Room exists, get landlord's name
        final landlordName = await _getUserName(landlordId);
        return ChatRoomModel.fromJson(data, landlordName);
      } else {
        // Room doesn't exist, create it
        final newData = await _client
            .from('chat_rooms')
            .insert({
              'tenant_id': tenantId,
              'landlord_id': landlordId,
            })
            .select()
            .single();
        
        final landlordName = await _getUserName(landlordId);
        return ChatRoomModel.fromJson(newData, landlordName);
      }
    } catch (e) {
      debugPrint(e.toString());
      rethrow;
    }
  }

  // 2. Get all chat rooms for a user
  Stream<List<ChatRoomModel>> getChatRooms(String userId, String userRole) async* {
    final String userColumn = userRole == 'tenant' ? 'tenant_id' : 'landlord_id';
    final String otherUserColumn = userRole == 'tenant' ? 'landlord_id' : 'tenant_id';
    
    // Fetch initial list of rooms
    final roomsData = await _client
        .from('chat_rooms')
        .select()
        .eq(userColumn, userId);

    List<ChatRoomModel> chatRooms = [];
    for (var roomData in roomsData) {
      final otherUserId = roomData[otherUserColumn];
      final otherUserName = await _getUserName(otherUserId);
      chatRooms.add(ChatRoomModel.fromJson(roomData, otherUserName));
    }
    yield chatRooms;
  }

  // 3. Stream messages from a specific room
  Stream<List<MessageModel>> getMessages(String roomId) {
    return _client
        .from('messages')
        .stream(primaryKey: ['id'])
        .eq('room_id', roomId)
        // --- THIS IS THE FIX ---
        .order('created_at', ascending: false) // Order by newest first
        // -----------------------
        .map((maps) => maps.map((map) => MessageModel.fromJson(map)).toList());
  }

  // 4. Send a new message
  Future<void> sendMessage(String roomId, String senderId, String content) async {
    try {
      final message = MessageModel(
        id: '', // Will be generated by DB
        roomId: roomId,
        senderId: senderId,
        content: content,
        createdAt: DateTime.now(), // Will be set by DB
      );
      await _client.from('messages').insert(message.toJson());
    } catch (e) {
      debugPrint(e.toString());
      rethrow;
    }
  }

  // Helper to get a user's name
  Future<String> _getUserName(String userId) async {
    try {
      final data = await _client
          .from('users')
          .select('name')
          .eq('id', userId)
          .single();
      return data['name'] ?? 'Unknown User';
    } catch (e) {
      return 'Unknown User';
    }
  }
}